In [25]:
import time
time.time()


1770822895.2701068

## ndarray indexing

Basic accessing and modifying of ndarrays


In [26]:
import numpy as np

In [27]:
np.random.seed(0)
randNums = np.random.uniform(-5,5,size = (5,4))

In [28]:
arr = randNums

In [29]:
# arr[0, :]
arr[0]

array([0.48813504, 2.15189366, 1.02763376, 0.44883183])

In [30]:
# access last 2 columns
print(arr)
print()
#print(arr[:, -2:]
#

[[ 0.48813504  2.15189366  1.02763376  0.44883183]
 [-0.76345201  1.45894113 -0.62412789  3.91773001]
 [ 4.63662761 -1.16558481  2.91725038  0.2889492 ]
 [ 0.68044561  4.25596638 -4.28963942 -4.128707  ]
 [-4.79781603  3.32619846  2.78156751  3.70012148]]



In [31]:
#access columns at indices 1-2 and in 1st row
# Low range (before :) contains that index
# High range (after :) does not contain that index (i-1)

print(arr)
print()
print(arr[0, 1:4])

[[ 0.48813504  2.15189366  1.02763376  0.44883183]
 [-0.76345201  1.45894113 -0.62412789  3.91773001]
 [ 4.63662761 -1.16558481  2.91725038  0.2889492 ]
 [ 0.68044561  4.25596638 -4.28963942 -4.128707  ]
 [-4.79781603  3.32619846  2.78156751  3.70012148]]

[2.15189366 1.02763376 0.44883183]


In [32]:
# Assign 1st row to -1s
arr[0, :] = -1
print(arr)

[[-1.         -1.         -1.         -1.        ]
 [-0.76345201  1.45894113 -0.62412789  3.91773001]
 [ 4.63662761 -1.16558481  2.91725038  0.2889492 ]
 [ 0.68044561  4.25596638 -4.28963942 -4.128707  ]
 [-4.79781603  3.32619846  2.78156751  3.70012148]]


In [33]:
# We want to reorder rows to swap 1st and last rows
arr = arr[[2,1,0],:]
print(arr)

[[ 4.63662761 -1.16558481  2.91725038  0.2889492 ]
 [-0.76345201  1.45894113 -0.62412789  3.91773001]
 [-1.         -1.         -1.         -1.        ]]


In [37]:
# arr[[0, -1], [0,2, 4]]
print(arr)
print(arr[np.ix_([0,-1], [0,2,4])])

[[ 4.63662761 -1.16558481  2.91725038  0.2889492 ]
 [-0.76345201  1.45894113 -0.62412789  3.91773001]
 [-1.         -1.         -1.         -1.        ]]


IndexError: index 4 is out of bounds for axis 1 with size 4

In [39]:
#fixed with .copy()
a = np.linspace(-1,1,5)
b=a.copy()
b[0]= 99
print(a)
print(b)

[-1.  -0.5  0.   0.5  1. ]
[99.  -0.5  0.   0.5  1. ]
