# Numpy and matrices tutorial

Oliver W. Layton

CS252: Mathematical Data Analysis and Visualization

Spring 2026


In [1]:
import numpy as np

## Switching around the axes of an ndarray and matrix multiplication in numpy


We can't matrix multiply the following ndarrays due to shape issues:


In [9]:
a = 3*np.ones([3, 4])
b = 2*np.ones([3, 4])
# c = a @ b.T
c = a.T @ b
d = a @ b.T
print(a.T.shape, d.T.shape)

(4, 3) (3, 3)


Need to pair up as

    (3, 4) x (4, 3)

OR

    (4, 3) x (3, 4)

Use the transpose to help out!


Note: Transposing a ndarray vector isn't meaningful if you don't have a singleton dimension


In [5]:
a = np.ones(10)
a.shape

(10,)

In [6]:
a[np.newaxis, :].shape

(1, 10)

In [7]:
a[np.newaxis, :].T.shape

(10, 1)

### Matrix vs. element-wise multiplication

- Star (\*) operator means element-wise multiplication
- Like other basic math operators, can use broadcasting (e.g. can multiply a (1,3) and a (5, 3) array)


In [10]:
a1 = 2*np.ones([1, 3])
b1 = 3*np.ones([5, 3])
a1 @ b1.T

array([[18., 18., 18., 18., 18.]])

In [14]:
print(np.sum(np.ones([1,2,3]),axis=1))
print(np.sum(np.ones([1,2,3]),axis=1).shape)

[[2. 2. 2.]]
(1, 3)


In [16]:
print(np.mean(np.random.random([20,10]), axis =0))
print(np.mean(np.random.random([20,10]), axis =1).shape)

[0.55081948 0.51647831 0.5856789  0.41435087 0.49809364 0.48067032
 0.50890104 0.50856153 0.49244021 0.51226555]
(20,)


In [23]:
print(np.zeros([5,5,5,5]))
print(np.zeros([5,5,5,5]).shape)

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]


In [25]:

print(np.squeeze(np.sum(np.zeros([5,4,2])[:,:,np.newaxis,:], axis = 0).shape))

[4 1 2]
