# NumPy tutorial

Oliver W. Layton

CS 251/2: Data Analysis and Visualization

Spring 2026


In [10]:
import numpy as np
import time

## Numpy ndarray basics


### Creation from Python lists


In [11]:
# Make a numpy array from a 2D python list
myList = [[1, 2, 3], [4, 5, 6]]
myArr = np.array(myList)

In [12]:
# print it
# print(myArr)
myArr

array([[1, 2, 3],
       [4, 5, 6]])

### Data type of ndarray


In [13]:
# determine data type
print('Type of array is\n', myArr.dtype)

Type of array is
 int64


Type can be changed in a few ways.

1. when creating array — (a) implicitly or (b) explicitly
2. by casting types.


In [14]:
# 1a implicitly
arr = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
arr.dtype

dtype('float64')

In [15]:
# 1b explicitly
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
arr.dtype


dtype('float64')

In [16]:
# 2. NOTE: This is a METHOD of the array, not a FUNCTION
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = arr.astype(float)
arr2.dtype

dtype('float64')

In [17]:
# Can also be string. be careful in your CSV parser that your "numbers"
# aren't actually strings!
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=str)
arr

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U1')

### Convert back to Python list


In [18]:
# Convert back from ndarray to Python list

print('Back as a Python list:\n', arrAsList)

NameError: name 'arrAsList' is not defined

### Other ways to create ndarrays quickly


#### 1. zeros

- We can plug in a list to get a multi-dimensional array
- We can plug in one int to get a vector of values


In [ ]:
myZeros = np.zeros([10, 5])
myZeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
myVec = np.zeros(3)
myVec

array([0., 0., 0.])

#### 2. ones


In [ ]:
ones = np.ones([2, 10])
print(ones)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
# can easily make any constant array
consts = -1*np.ones([10, 10])
consts

array([[-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.]])

#### 3. Random values


In [ ]:
# Uniform random values
rands = np.random.random([3, 4])
# rands = 10*np.random.random([3, 4])
rands

array([[6.28581032, 6.34760924, 0.71291109, 7.88440817],
       [8.69307299, 7.65622307, 8.83771799, 8.70793807],
       [9.52072756, 7.67192089, 8.30927156, 3.19013393]])

In [ ]:
myRands = np.random.uniform(low = 5, high=15, size=(2, 5))
myRands

array([[13.17906112,  5.27161921, 10.00140874,  5.53007131, 10.92612155],
       [ 9.7125812 , 14.55496605, 11.76172631, 11.05531995,  8.94023381]])

#### 4. Equally spaced floats in an interval


In [ ]:
# a = np.linspace(-10, 10)
a = np.linspace(-10, 10, 8)
a

array([-10.        ,  -7.14285714,  -4.28571429,  -1.42857143,
         1.42857143,   4.28571429,   7.14285714,  10.        ])

#### 5. Equally spaced ints in an interval


In [ ]:
# ints = np.arange(10)
ints = np.arange(-7, 10)
ints

array([-7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

#### 6. Identity matrix


In [ ]:
id = np.eye(10)
id

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Check dimensions — `shape`


In [ ]:
# check shape of 3D array
myArr3 = np.zeros([3, 4, 5])
print(myArr3.shape)
id.shape

(3, 4, 5)


(10, 10)

In [ ]:
# check number of dimensions (M)
id.ndim

2

In [ ]:
# Access 1st dim (#rows), 2nd dim (#cols) (Use f-string)
print(f'The array has {myArr3.shape[0]} rows and {myArr3.shape[1]} cols.')

The array has 3 rows and 4 cols.


In [ ]:
# Check number of elements total
print('Num elements in arr_1:', myArr3.size)

Num elements in arr_1: 60


In [ ]:
3*4*5

60

In [ ]:
# the familar Python len function works on ndarrays (any number of dims).
# It returns the shape (length) of the 1st dimension
print(len(myArr3))

3


## ndarray indexing

Basic Accessing and modifying of ndarrays.


### Access and modify single elements


In [ ]:
# To access elements in a multidimensional ndarray use ONE set of square brackets []
# Make a new random array
np.random.seed(0)  # ensures random numbers come up the same each time. Useful for debugging.
randNums = np.random.uniform(-5, 5, size=(5, 4))
randNums

array([[ 0.48813504,  2.15189366,  1.02763376,  0.44883183],
       [-0.76345201,  1.45894113, -0.62412789,  3.91773001],
       [ 4.63662761, -1.16558481,  2.91725038,  0.2889492 ],
       [ 0.68044561,  4.25596638, -4.28963942, -4.128707  ],
       [-4.79781603,  3.32619846,  2.78156751,  3.70012148]])

In [ ]:
# Get the 1st element
print(randNums[0, 0])

0.48813503927324753


In [19]:
# Modifying single values is similar

print('arr is now:\n', arr)

arr is now:
 [['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]


### Slicing: real power of numpy

Use **colon** notation for all values in a dimension

Access and modify different ranges of data along different dimensions


Make a 3x5 random array. Access 2nd column


In [20]:
np.random.seed(0)


In [21]:
# Make a 3x5 random array and access 2nd column
arr = np.random.uniform(low=-5, high=5, size=(3,5))  # not handwritten
arr[:, 1]  # 2nd column (index 1)

array([ 2.15189366, -0.62412789,  0.2889492 ])

Access 1st row


In [22]:
# Access first row of the array created above
arr[0, :]  # first row  (not handwritten)

array([ 0.48813504,  2.15189366,  1.02763376,  0.44883183, -0.76345201])

Access last 2 columns


In [23]:
# Access last two columns
arr[:, -2:]  # last 2 columns  (not handwritten)

array([[ 0.44883183, -0.76345201],
       [ 4.63662761, -1.16558481],
       [ 4.25596638, -4.28963942]])

Access columns at indices 1-2 and in 1st row. Careful about off-by-one.

- Low range (before :) CONTAINS that index
- High range (after :) DOES NOT contain that index (i-1)


In [24]:
# Access columns at indices 1-2 (inclusive of 1, exclusive of 3) in the 1st row
arr[0, 1:3]  # columns 1 and 2 from first row  (not handwritten)

array([2.15189366, 1.02763376])

Use slicing to assign values efficiently in batch without loops


In [25]:
# Assign 1st row to -1s
arr[0, :] = -1  # not handwritten
arr

array([[-1.        , -1.        , -1.        , -1.        , -1.        ],
       [ 1.45894113, -0.62412789,  3.91773001,  4.63662761, -1.16558481],
       [ 2.91725038,  0.2889492 ,  0.68044561,  4.25596638, -4.28963942]])

In [26]:
# Assign first row to increasing integers starting at 0
arr[0, :] = np.arange(arr.shape[1])  # not handwritten
arr

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 1.45894113, -0.62412789,  3.91773001,  4.63662761, -1.16558481],
       [ 2.91725038,  0.2889492 ,  0.68044561,  4.25596638, -4.28963942]])

In [27]:
# Multiply the 3rd row by 5 and update the row (index 2)
arr[2, :] = arr[2, :] * 5  # not handwritten
arr

array([[  0.        ,   1.        ,   2.        ,   3.        ,
          4.        ],
       [  1.45894113,  -0.62412789,   3.91773001,   4.63662761,
         -1.16558481],
       [ 14.5862519 ,   1.44474599,   3.40222805,  21.27983191,
        -21.44819709]])

Change order of rows (or columns) of a ndarray by indexing: Pass in a Python list of indices in the desired order.

This is useful for **shuffling data** (randomly reordering the data samples).


In [28]:
# Swap first and last rows in-place (works for 2D arrays)
arr[[0, -1]] = arr[[-1, 0]]  # not handwritten
arr

array([[ 14.5862519 ,   1.44474599,   3.40222805,  21.27983191,
        -21.44819709],
       [  1.45894113,  -0.62412789,   3.91773001,   4.63662761,
         -1.16558481],
       [  0.        ,   1.        ,   2.        ,   3.        ,
          4.        ]])

### What if we want to access a select set of rows in multiple columns?

Example: Say we want the first and last row and and columns 1, 3, and 5. If we try this with slicing, it won't work!

Can't use regular indexing notation. Instead use `np.ix_`


In [29]:
# This doesn't work!
# arr[[0, -1], [0, 2, 4]]

**Syntax for `np.ix_`:**

- `np.ix_` goes inside the square brackets: `arr[np.ix_(blah)]`
- Give it `M` arguments (e.g. 2 for a 2D matrix).
- Each argument is a Python list (or ndarray) of indices to take along that dimension.


In [30]:
# Example using np.ix_ to pick specific rows and columns
m = np.arange(1, 13).reshape(4, 3)  # 4x3 matrix  (not handwritten)
m[np.ix_([0, -1], [0, 2])]  # first and last row, cols 0 and 2

array([[ 1,  3],
       [10, 12]])

## Memory

- Numpy tries to be efficient with arrays so assignment does a shallow copy. To do a deep copy, you need to use `.copy()` method


In [31]:
a = np.linspace(-1, 1, 5)
a

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [32]:
# Demonstrate shallow copy / view: assign b = a (shallow)
b = a  # not handwritten
print(b)

[-1.  -0.5  0.   0.5  1. ]


In [33]:
# changed a!
a

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [34]:
# fixed with .copy()
c = a.copy()  # deep copy, modifications to c won't change a  (not handwritten)
c

array([-1. , -0.5,  0. ,  0.5,  1. ])

## Apply functions over dimensions (`axes`)

- Axes are the numpy term for different ndarray dimensions.
- _Idea_: Do we want to apply an operation (e.g. sum) on the rows OR columns of a ndarray?
- _Example_: axis 0 are the rows, axis 1 are the columns, etc.
- We can apply functions over one or more axis super efficiently in one line of code! This is called **Vectorization** — MUCH MUCH faster than loops (stay tuned).


In [35]:
one = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]])
one

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

Sum along rows -> "collapse" across rows to get sum within each column — 3 numbers


In [36]:
# Sum along rows -> collapse across rows to get sum for each column
one.sum(axis=0)  # not handwritten

array([10, 10, 10])

Sum along columns -> "collapse" across columns to get sum within each row — 4 numbers


In [37]:
# Sum along columns -> collapse across columns to get sum for each row
one.sum(axis=1)  # not handwritten

array([ 3,  6,  9, 12])

**Careful:** Applying a function without specifying the axis may compute across the ENTIRE ndarray.


In [38]:
# Applying a function without axis computes across entire ndarray
np.sum(one)  # not handwritten

np.int64(30)

**Mnemonic trick:** Applying a function along an axis eliminates that dimension from the shape. Left with remaining dimensions. (on quiz)


In [40]:
print(one.shape)

print(f'Mean across axis 0: {one.mean(axis=0)}')

print(one.shape)

print(f'Mean across axis 1: {}')

(4, 3)
Mean across axis 0: [2.5 2.5 2.5]
(4, 3)
Mean across axis 1: [1. 2. 3. 4.]


## Broadcasting (basics)

**This is the most useful numpy feature thus far! This will become your bread-and-butter!**

We will cover the basics now and revisit broadcasting in more detail in a few weeks.


### Broadcasting scalars

As we saw, we can create an array of any size with any constant value WITHOUT ANY LOOPS. This is the simplest example of numpy **broadcasting** the scalar across the ndarray.


In [41]:
# Example with basic arithmetic (broadcasting a scalar)
vec = np.array([1, 2, 3])  # not handwritten
vec + 5

array([6, 7, 8])

### Applying an operation to corresponding values in two arrays that have the same shape

Broadcasting allows you to efficiently (_and in one line of code_) add, subtract, multiply, and perform other operations on corresponding values in two arrays.


#### Examples: subtracting arrays with several different shapes


In [43]:
# 1D arrays
arr1 = np.arange(10)
arr2 = 5*np.ones(10)
print(f'arr1: {arr1}')
print(f'arr2: {arr2}')
print(f'Shape of arr1: {arr1.shape}')
print(f'Shape of arr2: {arr2.shape}')

arr3 = arr1 - arr2
print(arr3)
print(f'Shape of arr3: {arr3.shape}')

arr1: [0 1 2 3 4 5 6 7 8 9]
arr2: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
Shape of arr1: (10,)
Shape of arr2: (10,)
[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.]
Shape of arr3: (10,)


In [44]:
# 2D arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([[1, 1, 1], [0, 0, 0], [2, 2, 2]])
print(f'arr1:\n{arr1}')
print(f'arr2:\n{arr2}')
print(f'Shape of arr1: {arr1.shape}')
print(f'Shape of arr2: {arr2.shape}')

print(arr3)
print(f'Shape of arr3: {arr3.shape}')

arr1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2:
[[1 1 1]
 [0 0 0]
 [2 2 2]]
Shape of arr1: (3, 3)
Shape of arr2: (3, 3)
[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.]
Shape of arr3: (10,)


### Singleton dimensions

Sometimes you have a 1D array that has shape like `(blah,)` but you need to use broadcasting to subtract it with another array that has a shape of a **column vector** of a matrix `(blah, 1)`. Because the number of values in the two arrays match, you would think it would be possible to broadcast operations to corresponding values (e.g. subtract). BUT, broadcasting won't work like you want (let's try).


In [45]:
arr1 = np.arange(3)
arr2 = np.array([[1], [2], [3]])
print(f'arr1:\n{arr1}')
print(f'arr2:\n{arr2}')
print(f'arr1 shape: {arr1.shape}')
print(f'arr2 shape: {arr2.shape}')
print('Trying to broadcast arr1 - arr2...')


arr1:
[0 1 2]
arr2:
[[1]
 [2]
 [3]]
arr1 shape: (3,)
arr2 shape: (3, 1)
Trying to broadcast arr1 - arr2...


To get broadcasting to subtract off corresponding values in the arrays, we need to add a **singleton dimension** — an extra 1 dimension to `arr1` so that the shape matches the other array and so that numpy interprets `arr1` also as a column vector.


In [46]:
arr1 = np.arange(3)

print(f'arr1:\n{arr2}')
print(f'arr1 shape: {arr1.shape}')
print(f'arr2 shape: {arr2.shape}')
print('Trying to broadcast arr1 - arr2...')
arr3 = arr1 - arr2
arr3

arr1:
[[1]
 [2]
 [3]]
arr1 shape: (3,)
arr2 shape: (3, 1)
Trying to broadcast arr1 - arr2...


array([[-1,  0,  1],
       [-2, -1,  0],
       [-3, -2, -1]])

### Squeeze: How to get of all singleton dimensions

"Undo" a new axis / singleton dimension


In [48]:
# Show arr1 and arr2, demonstrating shapes (squeeze example follows)
print(f'arr1: {arr2}')  # not handwritten
print(f'arr1 shape: {arr1.shape}')

arr1: [[1]
 [2]
 [3]]
arr1 shape: (3,)


Removes ALL singleton dimensions (if you have more than one):


In [ ]:
# Remove singleton dimensions with squeeze
col = np.array([[1], [2], [3]])  # column vector  (not handwritten)
np.squeeze(col)

## Vectorization speed vs loops

Time computation of summing a ndarray with loop vs vectorized.


In [ ]:
def timeit(fun):
    '''Just a function to time the runtime of another function'''
    def timer():
        start = time.time()
        fun()
        end = time.time()
        print(f'Took {end - start:.3} secs to run.')
    return timer


@timeit
def sumLoop():
    '''Use for loop to sum a row vector'''
    longRow = np.array([i for i in range(1, 1000000)])
    theSum = 0
    for i in range(len(longRow)):
        theSum += longRow[i]


@timeit
def sumVectorized():
    '''Vectorized version of summing a row vector'''
    longRow = np.array([i for i in range(1, 1000000)])
    theSum = np.sum(longRow)

In [ ]:
# Dynamic typing in python makes for loops with lots of small
# operations slow
print('sumLoop:')
sumLoop()

# Vectorization allows Numpy to stop searching at runtime
# and use efficient pre-compiled functions to batch-process
# the computation over the matrix
print('sumVectorized:')
sumVectorized()

## Combining multiple ndarrays

**Problem:**

- You have two ndarrays and want to concatenate them
- You have an ndarray and **want to append a column or row vector**


### Add/append a new column — "stack horizontally"

**Mnemonic**: Columns go horizontally.

Have `a`:

    [[1, 2]
     [3, 4]]

and `b`

    [[9]
     [9]]

want to make:

    [[1, 2, 9]
     [3, 4, 9]]

i.e. stack horizontally. Could be two matrices (not just a matrix and a vector).

**Caveat:** We need to make sure shapes are compatible for broadcasting:

- Result shape = `(2, 3)`
- We are starting with `a` shape: `(2, 2)`

The shape of `b` needs to be `(2, 1)` (why?)


In [ ]:
# Stack horizontally: add a column vector to a matrix
a = np.array([[1, 2], [3, 4]])  # not handwritten
b = np.array([[9], [9]])
np.hstack((a, b))

In [ ]:
# Alternatively use concatenate along axis=1
a = np.array([[1, 2], [3, 4]])  # not handwritten
b = np.array([[9], [9]])
np.concatenate((a, b), axis=1)

## Sorting ndarrays

Numpy allows you to quickly sort numbers or strings.


In [ ]:
# Let's sort this array of random values between 0 and 1.
randArr = np.random.random(size=(100,))


In [ ]:
# Let's sort this list of words that start with different letters from 'a' to 'z'
word_list = ['leopard', 'apple', 'flamingo', 'giraffe', 'iguana', 'banana', 'yak', 'rhinoceros', 'zebra', 'cherry', \
             'jaguar', 'walrus', 'x-ray', 'hippo', 'narwhal', 'quokka', 'vulture', 'panda', 'squirrel', 'monkey', \
             'umbrella', 'ostrich', 'elephant', 'tiger', 'dog', 'kangaroo']


To reverse the order of an ndarray, you can use Python-like negative indexing notation


## Finding the index of the maximum item in an ndarray

This will come up at times during the semester.


In [ ]:
arr = np.array([1, 3, 7, 5])
idx = np.argmax(arr)  # not handwritten
print(f'The INDEX of the max item in arr is {idx}.')

The INDEX of the max item in arr is 2.


## Selecting random values from an ndarray

Let's say we wanted to pick out two **different** random values from the ndarray `arr`.

_This will come up later in the semester._


In [ ]:
arr = np.array([1, 3, 7, 5])
# pick two different random values without replacement
items = np.random.choice(arr, size=2, replace=False)  # not handwritten
print(f'The two randomly selected values from arr are: {items}.')

quiz
